name: Seek Scraper
on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm install playwright ts-node@10.9.1 typescript@5.0.4 @types/node@18
          npx playwright install chromium --with-deps
          
      - name: Run Scraper
        env:
          PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
          PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
        run: npx ts-node --project tsconfig.json seek-scraper.ts
